---
# Basic info on the node   

- hosts: localhost
  gather_facts: false

  tasks:
  # whoami  
  - name: Save the result of 'whoami' in 'whoami_out'
    raw: whoami
    register: whoami_out

  # hostname  
  - name: Save the result of 'hostname' in 'host'
    raw: hostname
    register: host

  # nslookup  (dig only works on linux architectures)  
  - name: nslookup  
    raw: "nslookup {{ host }}"
    register: ns_lookup_out



  # List outputs  
  - name: "Accessing {{ host }} with account: {{ whoami_out.stdout }}"
    debug:
      msg: "Accessing {{ host }} with account: {{ whoami_out.stdout }}"
